#' Identify the First Year a Variable Was Introduced
#'
#' @param missing_df The output data frame from `missing_percentage_by_group()`.
#'
#' @return A data frame with variables and the first year they were introduced.
#' @import data.table
#' @export
#'
#' @examples
#' df <- data.frame(
#'   date_var = seq(as.Date("2020-01-01"), by = "year", length.out = 6),
#'   var1 = c(NA, NA, 3, 4, 5, 6),
#'   var2 = c(NA, NA, NA, 7, 8, 9)
#' )
#' missing_by_year <- missing_percentage_by_group(df, "date_var", year)
#' first_intro_year <- find_first_introduction_year(missing_by_year)
#' print(first_intro_year)

find_first_introduction_year <- function(missing_df) {
  # Validate input
  if (!is.data.frame(missing_df)) {
    stop("Error: 'missing_df' must be a data frame generated by missing_percentage_by_group().")
  }
  
  # Extract years from column names (excluding var_name column)
  years <- as.numeric(colnames(missing_df)[-ncol(missing_df)])  # Convert to numeric years
  
  # Data frame to store first year of introduction
  first_years <- data.frame(variable = character(), first_year = numeric(), stringsAsFactors = FALSE)

  # Process each variable row (skip var_name)
  for (i in seq_len(nrow(missing_df))) {
    var_name <- missing_df$var_name[i]
    
    # Extract missing value percentages and convert to numeric
    missing_vals <- as.numeric(missing_df[i, -ncol(missing_df)])
    
    # Find first drop from 100% to lower values for two consecutive years
    for (j in seq_along(missing_vals)[-1]) {
      if (missing_vals[j - 1] == 100 && missing_vals[j] < 100) {
        if (j + 1 <= length(missing_vals) && missing_vals[j + 1] < 100) {
          first_years <- rbind(first_years, data.frame(variable = var_name, first_year = years[j]))
          break
        }
      }
    }
  }

  return(first_years)
}
